# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QStringListModel

from GUI.Account_setting import Ui_Login_window
from GUI.Send import Ui_Send_window
from utils.handelers.receive import receive, get_all
from utils.handelers.delete import delete_email


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Compose_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Compose_pushButton.setGeometry(QtCore.QRect(10, 60, 121, 23))
        self.Compose_pushButton.setObjectName("Compose_pushButton")
        self.Inbox_list = QtWidgets.QListView(self.centralwidget)
        self.Inbox_list.setGeometry(QtCore.QRect(10, 90, 121, 321))
        self.Inbox_list.setObjectName("Inbox_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.From_label = QtWidgets.QLabel(self.centralwidget)
        self.From_label.setGeometry(QtCore.QRect(280, 50, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.From_label.setFont(font)
        self.From_label.setObjectName("From_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Subject_label = QtWidgets.QLabel(self.centralwidget)
        self.Subject_label.setGeometry(QtCore.QRect(280, 80, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Subject_label.setFont(font)
        self.Subject_label.setObjectName("Subject_label")
        self.Content = QtWidgets.QTextBrowser(self.centralwidget)
        self.Content.setGeometry(QtCore.QRect(210, 110, 421, 311))
        self.Content.setObjectName("Content")
        self.Account_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Account_pushButton.setGeometry(QtCore.QRect(10, 30, 51, 23))
        self.Account_pushButton.setObjectName("Account_pushButton")
        self.Delete_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_pushButton.setGeometry(QtCore.QRect(70, 30, 61, 23))
        self.Delete_pushButton.setObjectName("Delete_pushButton")
        self.Refresh_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh_pushButton.setGeometry(QtCore.QRect(10, 0, 121, 23))
        self.Refresh_pushButton.setObjectName("Refresh_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Account_pushButton.clicked.connect(self.account_settings)
        self.Compose_pushButton.clicked.connect(self.send_mail)
        self.Refresh_pushButton.clicked.connect(self.receive_mail)
        self.Delete_pushButton.clicked.connect(self.delete)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My Mail"))
        self.Compose_pushButton.setText(_translate("MainWindow", "Compose New"))
        self.label.setText(_translate("MainWindow", "From"))
        self.From_label.setText(_translate("MainWindow", "N/A"))
        self.label_3.setText(_translate("MainWindow", "Subjecct"))
        self.Subject_label.setText(_translate("MainWindow", "N/A"))
        self.Account_pushButton.setText(_translate("MainWindow", "Account"))
        self.Delete_pushButton.setText(_translate("MainWindow", "Delete"))
        self.Refresh_pushButton.setText(_translate("MainWindow", "Refresh"))
    def account_settings(self):
        self.form_account = QtWidgets.QWidget()
        self.ui_account = Ui_Login_window()
        self.ui_account.setupUi(self.form_account)
        self.form_account.show()
    def send_mail(self):
        self.form_send = QtWidgets.QMainWindow()
        self.ui_send = Ui_Send_window()
        self.ui_send.setupUi(self.form_send)
        self.form_send.show()
    def receive_mail(self):
        receive()
        model = QStringListModel()
        emails = get_all()
        model.setStringList([str(email['subject']) for email in emails])
        self.index_list = {}
        for i in range(len(emails)):
            self.index_list[i] = emails[i]['id']
        self.Inbox_list.setModel(model)
        self.Inbox_list.clicked.connect(self.show_email)
    def show_email(self):
        emails = get_all()
        index = self.Inbox_list.currentIndex().row()
        self.From_label.setText(emails[index]['sender'])
        self.Subject_label.setText(emails[index]['subject'])
        self.Content.setText(emails[index]['content'])
    def delete(self):
        index = self.Inbox_list.currentIndex().row()
        delete_email(self.index_list[index])
        self.receive_mail()

