# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Send.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.handlers.send import send_mail

class Ui_Send_window(object):
    def setupUi(self, Send_window):
        Send_window.setObjectName("Send_window")
        Send_window.resize(703, 501)
        self.centralwidget = QtWidgets.QWidget(Send_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 90, 571, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_1.addWidget(self.label_2)
        self.To_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.To_lineEdit.setObjectName("To_lineEdit")
        self.horizontalLayout_1.addWidget(self.To_lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 140, 571, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Subject_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.Subject_lineEdit.setObjectName("Subject_lineEdit")
        self.horizontalLayout_2.addWidget(self.Subject_lineEdit)
        self.Content_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Content_textEdit.setGeometry(QtCore.QRect(50, 200, 571, 201))
        self.Content_textEdit.setObjectName("Content_textEdit")
        self.Send_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Send_pushButton.setGeometry(QtCore.QRect(550, 420, 75, 23))
        self.Send_pushButton.setObjectName("Send_pushButton")
        Send_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Send_window)
        self.statusbar.setObjectName("statusbar")
        Send_window.setStatusBar(self.statusbar)

        self.retranslateUi(Send_window)
        QtCore.QMetaObject.connectSlotsByName(Send_window)
        self.Send_pushButton.clicked.connect(self.send_mail)

    def retranslateUi(self, Send_window):
        _translate = QtCore.QCoreApplication.translate
        Send_window.setWindowTitle(_translate("Send_window", "MainWindow"))
        self.label.setText(_translate("Send_window", "New Mail"))
        self.label_2.setText(_translate("Send_window", "To   "))
        self.label_3.setText(_translate("Send_window", "Subject"))
        self.Send_pushButton.setText(_translate("Send_window", "Send"))
    def send_mail(self):
        to = self.To_lineEdit.text()
        subject = self.Subject_lineEdit.text()
        content = self.Content_textEdit.toPlainText()
        result = send_mail(to, subject, content)
        if result == "Success":
            self.statusbar.showMessage("Mail sent successfully")
        else:
            self.statusbar.showMessage(result)